'''
Most of the code in this file taken from RibosomeXYZ:
A. Kushner, A.S. Petrov, K. Dao Duc, (2022) “RiboXYZ: A comprehensive database for ribosome structures”,  Nucleic Acids Research, gkac939
(https://github.com/rtviii/riboxyz/blob/master/ribctl/lib/schema/types_binding_site.py)
'''

import typing
from pydantic import BaseModel
from Bio.PDB.Residue import Residue

AMINO_ACIDS = {
    "ALA": {"one_letter_code": "A", "charge": 0},
    "ARG": {"one_letter_code": "R", "charge": 1},
    "ASN": {"one_letter_code": "N", "charge": 0},
    "ASP": {"one_letter_code": "D", "charge": -1},
    "CYS": {"one_letter_code": "C", "charge": 0},
    "GLU": {"one_letter_code": "E", "charge": -1},
    "GLN": {"one_letter_code": "Q", "charge": 0},
    "GLY": {"one_letter_code": "G", "charge": 0},
    "HIS": {"one_letter_code": "H", "charge": 0},
    "ILE": {"one_letter_code": "I", "charge": 0},
    "LEU": {"one_letter_code": "L", "charge": 0},
    "LYS": {"one_letter_code": "K", "charge": 1},
    "MET": {"one_letter_code": "M", "charge": 0},
    "PHE": {"one_letter_code": "F", "charge": 0},
    "PRO": {"one_letter_code": "P", "charge": 0},
    "SER": {"one_letter_code": "S", "charge": 0},
    "THR": {"one_letter_code": "T", "charge": 0},
    "TRP": {"one_letter_code": "W", "charge": 0},
    "TYR": {"one_letter_code": "Y", "charge": 0},
    "VAL": {"one_letter_code": "V", "charge": 0},
}
NUCLEOTIDES = ["A", "T", "C", "G", "U"]

PROTOTYPES = {
    "eukaryota": {
        "uL4": {
            'parent_id': '4ug0', 
            'auth_asym_id': 'LC', 
            'seq': 'MACARPLISVYSEKGESSGKNVTLPAVFKAPIRPDIVNFVHTNLRKNNRQPYAVSELAGHQTSAESWGTGRAVARIPRVRGGGTHRSGQGAFGNMCRGGRMFAPTKTWRRWHRRVNTTQKRYAICSALAASALPALVMSKGHRIEEVPELPLVVEDKVEGYKKTKEAVLLLKKLKAWNDIKKVYASQRMRAGKGKMRNRRRIQRRGPCIIYNEDNGIIKAFRNIPGITLLNVSKLNILKLAPGGHVGRFCIWTESAFRKLDELYGTWRKAASLKSNYNLPMHKMINTDLSRILKSPEIQRALRAPRKKIHRRVLKKNPLKNLRIMLKLNPYAKTMRRNTILRQARNHKLRVDKAAAAAAALQAKSDEKAAVAGKKPVVGKKGKKAAVGVKKQKKPLVGKKAAATKKPAPEKKPAEKKPTTEEKKPAA'
        },
        "uL22": {
            'parent_id': '4ug0', 
            'auth_asym_id': 'LP', 
            'seq': 'MVRYSLDPENPTKSCKSRGSNLRVHFKNTRETAQAIKGMHIRKATKYLKDVTLQKQCVPFRRYNGGVGRCAQAKQWGWTQGRWPKKSAEFLLHMLKNAESNAELKGLDVDSLVIEHIQVNKAPKMRRRTYRAHGRINPYMSSPCHIEMILTEKEQIVPKPEEEVAQKKKISQKKLKKQKLMARE'
        },
        "eL39": {
            'parent_id': '4ug0',
            'auth_asym_id': 'Ll',
            'seq': 'MSSHKTFRIKRFLAKKQKQNRPIPQWIRMKTGNKIRYNSKRRHWRRTKLGL'  
        },
        "25-28S": {
            'parent_id': '4ug0', 
            'auth_asym_id': 'L5', 
            'seq': 'CGCGACCUCAGAUCAGACGUGGCGACCCGCUGAAUUUAAGCAUAUUAGUCAGCGGAGGAGAAGAAACUAACCAGGAUUCCCUCAGUAACGGCGAGUGAACAGGGAAGAGCCCAGCGCCGAAUCCCCGCCCCGCGGCGGGGCGCGGGACAUGUGGCGUACGGAAGACCCGCUCCCCGGCGCCGCUCGUGGGGGGCCCAAGUCCUUCUGAUCGAGGCCCAGCCCGUGGACGGUGUGAGGCCGGUAGCGGCCCCCGGCGCGCCGGGCCCGGGUCUUCCCGGAGUCGGGUUGCUUGGGAAUGCAGCCCAAAGCGGGUGGUAAACUCCAUCUAAGGCUAAAUACCGGCACGAGACCGAUAGUCAACAAGUACCGUAAGGGAAAGUUGAAAAGAACUUUGAAGAGAGAGUUCAAGAGGGCGUGAAACCGUUAAGAGGUAAACGGGUGGGGUCCGCGCAGUCCGCCCGGAGGAUUCAACCCGGCGGCGGGUCCGGCCGUGUCGGCGGCCCGGCGGAUCUUUCCCGCCCCCCGUUCCUCCCGACCCCUCCACCCGCCCUCCCUUCCCCCGCCGCCCCUCCUCCUCCUCCCCGGAGGGGGCGGGCUCCGGCGGGUGCGGGGGUGGGCGGGCGGGGCCGGGGGUGGGGUCGGCGGGGGACCGUCCCCCGACCGGCGACCGGCCGCCGCCGGGCGCAUUUCCACCGCGGCGGUGCGCCGCGACCGGCUCCGGGACGGCUGGGAAGGCCCGGCGGGGAAGGUGGCUCGGGGGGCCCCGUCCGUCCGUCCGUCCGUCCUCCUCCUCCCCCGUCUCCGCCCCCCGGCCCCGCGUCCUCCCUCGGGAGGGCGCGCGGGUCGGGGCGGCGGCGGCGGCGGCGGUGGCGGCGGCGGCGGCGGCGGCGGGACCGAAACCCCCCCCGAGUGUUACAGCCCCCCCGGCAGCAGCACUCGCCGAAUCCCGGGGCCGAGGGAGCGAGACCCGUCGCCGCGCUCUCCCCCCUCCCGGCGCCCACCCCCGCGGGGAAUCCCCCGCGAGGGGGGUCUCCCCCGCGGGGGCGCGCCGGCGUCUCCUCGUGGGGGGGCCGGGCCACCCCUCCCACGGCGCGACCGCUCUCCCACCCCUCCUCCCCGCGCCCCCGCCCCGGCGACGGGGGGGGUGCCGCGCGCGGGUCGGGGGGCGGGGCGGACUGUCCCCAGUGCGCCCCGGGCGGGUCGCGCCGUCGGGCCCGGGGGAGGUUCUCUCGGGGCCACGCGCGCGUCCCCCGAAGAGGGGGACGGCGGAGCGAGCGCACGGGGUCGGCGGCGACGUCGGCUACCCACCCGACCCGUCUUGAAACACGGACCAAGGAGUCUAACACGUGCGCGAGUCGGGGGCUCGCACGAAAGCCGCCGUGGCGCAAUGAAGGUGAAGGCCGGCGCGCUCGCCGGCCGAGGUGGGAUCCCGAGGCCUCUCCAGUCCGCCGAGGGCGCACCACCGGCCCGUCUCGCCCGCCGCGCCGGGGAGGUGGAGCACGAGCGCACGUGUUAGGACCCGAAAGAUGGUGAACUAUGCCUGGGCAGGGCGAAGCCAGAGGAAACUCUGGUGGAGGUCCGUAGCGGUCCUGACGUGCAAAUCGGUCGUCCGACCUGGGUAUAGGGGCGAAAGACUAAUCGAACCAUCUAGUAGCUGGUUCCCUCCGAAGUUUCCCUCAGGAUAGCUGGCGCUCUCGCAGACCCGACGCACCCCCGCCACGCAGUUUUAUCCGGUAAAGCGAAUGAUUAGAGGUCUUGGGGCCGAAACGAUCUCAACCUAUUCUCAAACUUUAAAUGGGUAAGAAGCCCGGCUCGCUGGCGUGGAGCCGGGCGUGGAAUGCGAGUGCCUAGUGGGCCACUUUUGGUAAGCAGAACUGGCGCUGCGGGAUGAACCGAACGCCGGGUUAAGGCGCCCGAUGCCGACGCUCAUCAGACCCCAGAAAAGGUGUUGGUUGAUAUAGACAGCAGGACGGUGGCCAUGGAAGUCGGAAUCCGCUAAGGAGUGUGUAACAACUCACCUGCCGAAUCAACUAGCCCUGAAAAUGGAUGGCGCUGGAGCGUCGGGCCCAUACCCGGCCGUCGCCGGCAGUCGAGAGUGGACGGGAGCGGCGGGGGCGGCGCGCGCGCGCGCGCGUGUGGUGUGCGUCGGAGGGCGGCGGCGGCGGCGGCGGCGGGGGUGUGGGGUCCUUCCCCCGCCCCCCCCCCCACGCCUCCUCCCCUCCUCCCGCCCACGCCCCGCUCCCCGCCCCCGGAGCCCCGCGGACGCUACGCCGCGACGAGUAGGAGGGCCGCUGCGGUGAGCCUUGAAGCCUAGGGCGCGGGCCCGGGUGGAGCCGCCGCAGGUGCAGAUCUUGGUGGUAGUAGCAAAUAUUCAAACGAGAACUUUGAAGGCCGAAGUGGAGAAGGGUUCCAUGUGAACAGCAGUUGAACAUGGGUCAGUCGGUCCUGAGAGAUGGGCGAGCGCCGUUCCGAAGGGACGGGCGAUGGCCUCCGUUGCCCUCGGCCGAUCGAAAGGGAGUCGGGUUCAGAUCCCCGAAUCCGGAGUGGCGGAGAUGGGCGCCGCGAGGCGUCCAGUGCGGUAACGCGACCGAUCCCGGAGAAGCCGGCGGGAGCCCCGGGGAGAGUUCUCUUUUCUUUGUGAAGGGCAGGGCGCCCUGGAAUGGGUUCGCCCCGAGAGAGGGGCCCGUGCCUUGGAAAGCGUCGCGGUUCCGGCGGCGUCCGGUGAGCUCUCGCUGGCCCUUGAAAAUCCGGGGGAGAGGGUGUAAAUCUCGCGCCGGGCCGUACCCAUAUCCGCAGCAGGUCUCCAAGGUGAACAGCCUCUGGCAUGUUGGAACAAUGUAGGUAAGGGAAGUCGGCAAGCCGGAUCCGUAACUUCGGGAUAAGGAUUGGCUCUAAGGGCUGGGUCGGUCGGGCUGGGGCGCGAAGCGGGGCUGGGCGCGCGCCGCGGCUGGACGAGGCGCCGCCGCCCCCCCCACGCCCGGGGCACCCCCCUCGCGGCCCUCCCCCGCCCCACCCCGCGCGCGCCGCUCGCUCCCUCCCCGCCCCGCGCCCUCUCUCUCUCUCUCUCCCCCGCUCCCCGUCCUCCCCCCUCCCCGGGGGAGCGCCGCGUGGGGGCGGCGGCGGGGGGAGAAGGGUCGGGGCGGCAGGGGCCGGCGGCGGCCCGCCGCGGGGCCCCGGCGGCGGGGGCACGGUCCCCCGCGAGGGGGGCCCGGGCACCCGGGGGGCCGGCGGCGGCGGCGACUCUGGACGCGAGCCGGGCCCUUCCCGUGGAUCGCCCCAGCUGCGGCGGGCGUCGCGGCCGCCCCCGGGGAGCCCGGCGGGCGCCGGCGCGCCCCCCCCCCCACCCCACGUCUCGUCGCGCGCGCGUCCGCUGGGGGCGGGGAGCGGUCGGGCGGCGGCGGUCGGCGGGCGGCGGGGCGGGGCGGUUCGUCCCCCCGCCCUACCCCCCCGGCCCCGUCCGCCCCCCGUUCCCCCCUCCUCCUCGGCGCGCGGCGGCGGCGGCGGCAGGCGGCGGAGGGGCCGCGGGCCGGUCCCCCCCGCCGGGUCCGCCCCCGGGGCCGCGGUUCCGCGCGGCGCCUCGCCUCGGCCGGCGCCUAGCAGCCGACUUAGAACUGGUGCGGACCAGGGGAAUCCGACUGUUUAAUUAAAACAAAGCAUCGCGAAGGCCCGCGGCGGGUGUUGACGCGAUGUGAUUUCUGCCCAGUGCUCUGAAUGUCAAAGUGAAGAAAUUCAAUGAAGCGCGGGUAAACGGCGGGAGUAACUAUGACUCUCUUAAGGUAGCCAAAUGCCUCGUCAUCUAAUUAGUGACGCGCAUGAAUGGAUGAACGAGAUUCCCACUGUCCCUACCUACUAUCCAGCGAAACCACAGCCAAGGGAACGGGCUUGGCGGAAUCAGCGGGGAAAGAAGACCCUGUUGAGCUUGACUCUAGUCUGGCACGGUGAAGAGACAUGAGAGGUGUAGAAUAAGUGGGAGGCCCCCGGCGCCCCCCCGGUGUCCCCGCGAGGGGCCCGGGGCGGGGUCCGCCGGCCCUGCGGGCCGCCGGUGAAAUACCACUACUCUGAUCGUUUUUUCACUGACCCGGUGAGGCGGGGGGGCGAGCCCCGAGGGGCUCUCGCUUCUGGCGCCAAGCGCCCGGCCGCGCGCCGGCCGGGCGCGACCCGCUCCGGGGACAGUGCCAGGUGGGGAGUUUGACUGGGGCGGUACACCUGUCAAACGGUAACGCAGGUGUCCUAAGGCGAGCUCAGGGAGGACAGAAACCUCCCGUGGAGCAGAAGGGCAAAAGCUCGCUUGAUCUUGAUUUUCAGUACGAAUACAGACCGUGAAAGCGGGGCCUCACGAUCCUUCUGACCUUUUGGGUUUUAAGCAGGAGGUGUCAGAAAAGUUACCACAGGGAUAACUGGCUUGUGGCGGCCAAGCGUUCAUAGCGACGUCGCUUUUUGAUCCUUCGAUGUCGGCUCUUCCUAUCAUUGUGAAGCAGAAUUCACCAAGCGUUGGAUUGUUCACCCACUAAUAGGGAACGUGAGCUGGGUUUAGACCGUCGUGAGACAGGUUAGUUUUACCCUACUGAUGAUGUGUUGUUGCCAUGGUAAUCCUGCUCAGUACGAGAGGAACCGCAGGUUCAGACAUUUGGUGUAUGUGCUUGGCUGAGGAGCCAAUGGGGCGAAGCUACCAUCUGUGGGAUUAUGACUGAACGCCUCUAAGUCAGAAUCCCGCCCAGGCGGAACGAUACGGCAGCGCCGCGGAGCCUCGGUUGGCCUCGGAUAGCCGGUCCCCCGCCUGUCCCCGCCGGCGGGCCGCCCCCCCCCUCCACGCGCCCCGCGCGCGCGGGAGGGCGCGUGCCCCGCCGCGCGCCGGGACCGGGGUCCGGUGCGGAGUGCCCUUCGUCCUGGGAAACGGGGCGCGGCCGGAGAGGCGGCCGCCCCCUCGCCCGUCACGCACCGGCCGUUCGUGGGGAACCUGGCGCUAAACCAUUCGUAGACGACCUGCUUCUGGGUCGGGGUUUCGUACGUAGCAGAGCAGCUCCCUCGCUGCGAUCUAUUGAAAGUCAGCCCUCGACACAAGGGUUUGUC'
        }
    },
    "bacteria": {
        "uL4": {
            'parent_id': '3J7Z', 
            'auth_asym_id': 'E', 
            'seq': 'MELVLKDAQSALTVSETTFGRDFNEALVHQVVVAYAAGARQGTRAQKTRAEVTGSGKKPWRQKGTGRARSGSIKSPIWRSGGVTFAARPQDHSQKVNKKMYRGALKSILSELVRQDRLIVVEKFSVEAPKTKLLAQKLKDMALEDVLIITGELDENLFLAARNLHKVDVRDATGIDPVSLIAFDKVVMTADAVKQVEEMLA'
        },
        "uL22": {
            'parent_id': '3J7Z', 
            'auth_asym_id': 'S', 
            'seq': 'METIAKHRHARSSAQKVRLVADLIRGKKVSQALDILTYTNKKAAVLVKKVLESAIANAEHNDGADIDDLKVTKIFVDEGPSMKRIMPRAKGRADRILKRTSHITVVVSDR'
        },
        "uL23": {
            'parent_id': '3J7Z', 
            'auth_asym_id': 'T', 
            'seq': 'MIREERLLKVLRAPHVSEKASTAMEKSNTIVLKVAKDATKAEIKAAVQKLFEVEVEVVNTLVVKGKVKRHGQRIGRRSDWKKAYVTLKEGQNLDFVGGAE'
        },
        "23S": {
            'parent_id': '3J7Z', 
            'auth_asym_id': 'A', 
            'seq': 'GGUUAAGCGACUAAGCGUACACGGUGGAUGCCCUGGCAGUCAGAGGCGAUGAAGGACGUGCUAAUCUGCGAUAAGCGUCGGUAAGGUGAUAUGAACCGUUAUAACCGGCGAUUUCCGAAUGGGGAAACCCAGUGUGUUUCGACACACUAUCAUUAACUGAAUCCAUAGGUUAAUGAGGCGAACCGGGGGAACUGAAACAUCUAAGUACCCCGAGGAAAAGAAAUCAACCGAGAUUCCCCCAGUAGCGGCGAGCGAACGGGGAGCAGCCCAGAGCCUGAAUCAGUGUGUGUGUUAGUGGAAGCGUCUGGAAAGGCGCGCGAUACAGGGUGACAGCCCCGUACACAAAAAUGCACAUGCUGUGAGCUCGAUGAGUAGGGCGGGACACGUGGUAUCCUGUCUGAAUAUGGGGGGACCAUCCUCCAAGGCUAAAUACUCCUGACUGACCGAUAGUGAACCAGUACCGUGAGGGAAAGGCGAAAAGAACCCCGGCGAGGGGAGUGAAAAAGAACCUGAAACCGUGUACGUACAAGCAGUGGGAGCACGCUUAGGCGUGUGACUGCGUACCUUUUGUAUAAUGGGUCAGCGACUUAUAUUCUGUAGCAAGGUUAACCGAAUAGGGGAGCCGAAGGGAAACCGAGUCUUAACUGGGCGUUAAGUUGCAGGGUAUAGACCCGAAACCCGGUGAUCUAGCCAUGGGCAGGUUGAAGGUUGGGUAACACUAACUGGAGGACCGAACCGACUAAUGUUGAAAAAUUAGCGGAUGACUUGUGGCUGGGGGUGAAAGGCCAAUCAAACCGGGAGAUAGCUGGUUCUCCCCGAAAGCUAUUUAGGUAGCGCCUCGUGAAUUCAUCUCCGGGGGUAGAGCACUGUUUCGGCAAGGGGGUCAUCCCGACUUACCAACCCGAUGCAAACUGCGAAUACCGGAGAAUGUUAUCACGGGAGACACACGGCGGGUGCUAACGUCCGUCGUGAAGAGGGAAACAACCCAGACCGCCAGCUAAGGUCCCAAAGUCAUGGUUAAGUGGGAAACGAUGUGGGAAGGCCCAGACAGCCAGGAUGUUGGCUUAGAAGCAGCCAUCAUUUAAAGAAAGCGUAAUAGCUCACUGGUCGAGUCGGCCUGCGCGGAAGAUGUAACGGGGCUAAACCAUGCACCGAAGCUGCGGCAGCGACGCUUAUGCGUUGUUGGGUAGGGGAGCGUUCUGUAAGCCUGCGAAGGUGUGCUGUGAGGCAUGCUGGAGGUAUCAGAAGUGCGAAUGCUGACAUAAGUAACGAUAAAGCGGGUGAAAAGCCCGCUCGCCGGAAGACCAAGGGUUCCUGUCCAACGUUAAUCGGGGCAGGGUGAGUCGACCCCUAAGGCGAGGCCGAAAGGCGUAGUCGAUGGGAAACAGGUUAAUAUUCCUGUACUUGGUGUUACUGCGAAGGGGGGACGGAGAAGGCUAUGUUGGCCGGGCGACGGUUGUCCCGGUUUAAGCGUGUAGGCUGGUUUUCCAGGCAAAUCCGGAAAAUCAAGGCUGAGGCGUGAUGACGAGGCACUACGGUGCUGAAGCAACAAAUGCCCUGCUUCCAGGAAAAGCCUCUAAGCAUCAGGUAACAUCAAAUCGUACCCCAAACCGACACAGGUGGUCAGGUAGAGAAUACCAAGGCGCUUGAGAGAACUCGGGUGAAGGAACUAGGCAAAAUGGUGCCGUAACUUCGGGAGAAGGCACGCUGAUAUGUAGGUGAGGUCCCUCGCGGAUGGAGCUGAAAUCAGUCGAAGAUACCAGCUGGCUGCAACUGUUUAUUAAAAACACAGCACUGUGCAAACACGAAAGUGGACGUAUACGGUGUGACGCCUGCCCGGUGCCGGAAGGUUAAUUGAUGGGGUUAGCGCAAGCGAAGCUCUUGAUCGAAGCCCCGGUAAACGGCGGCCGUAACUAUAACGGUCCUAAGGUAGCGAAAUUCCUUGUCGGGUAAGUUCCGACCUGCACGAAUGGCGUAAUGAUGGCCAGGCUGUCUCCACCCGAGACUCAGUGAAAUUGAACUCGCUGUGAAGAUGCAGUGUACCCGCGGCAAGACGGAAAGACCCCGUGAACCUUUACUAUAGCUUGACACUGAACAUUGAGCCUUGAUGUGUAGGAUAGGUGGGAGGCUUUGAAGUGUGGACGCCAGUCUGCAUGGAGCCGACCUUGAAAUACCACCCUUUAAUGUUUGAUGUUCUAACGUUGACCCGUAAUCCGGGUUGCGGACAGUGUCUGGUGGGUAGUUUGACUGGGGCGGUCUCCUCCUAAAGAGUAACGGAGGAGCACGAAGGUUGGCUAAUCCUGGUCGGACAUCAGGAGGUUAGUGCAAUGGCAUAAGCCAGCUUGACUGCGAGCGUGACGGCGCGAGCAGGUGCGAAAGCAGGUCAUAGUGAUCCGGUGGUUCUGAAUGGAAGGGCCAUCGCUCAACGGAUAAAAGGUACUCCGGGGAUAACAGGCUGAUACCGCCCAAGAGUUCAUAUCGACGGCGGUGUUUGGCACCUCGAUGUCGGCUCAUCACAUCCUGGGGCUGAAGUAGGUCCCAAGGGUAUGGCUGUUCGCCAUUUAAAGUGGUACGCGAGCUGGGUUUAGAACGUCGUGAGACAGUUCGGUCCCUAUCUGCCGUGGGCGCUGGAGAACUGAGGGGGGCUGCUCCUAGUACGAGAGGACCGGAGUGGACGCAUCACUGGUGUUCGGGUUGUCAUGCCAAUGGCACUGCCCGGUAGCUAAAUGCGGAAGAGAUAAGUGCUGAAAGCAUCUAAGCACGAAACUUGCCCCGAGAUGAGUUCUCCCUGACCCUUUAAGGGUCCUGAAGGAACGUUGAAGACGACGACGUUGAUAGGCCGGGUGUGUAAGCGCAGCGAUGCGUUGAGCUAACCGGUACUAAUGAACCGUGAGGCUUAACCU'
        }
    },
    "archaea": {
        "uL4": {
            'parent_id': '4V6U', 
            'auth_asym_id': 'BD', 
            'seq': 'MKVKVFDLNGQPVGEIELPKVFFTPFRPDLIRRAVIASWTHRIQPQGRDPMAGKRRVTENIGKGHSMARVERLKTPPRYAAFVPFARGGRRTHPPKVEKIIWEDINKKEKRLALMSAIAATANYDLVRARGHIIDNVPQLPLIVVDDLQKVQKTRETREIFKKLGIWDDIVRAKEKSGVRAGKGKMRGRRYKKAKGPLIVVGKNEGIVLGARNHPGVDVVVVDNLGVEHLAPGTHPGRLTVWTVSAIERLRELYG'
        },
        "uL22": {
            'parent_id': '4V6U', 
            'auth_asym_id': 'BS', 
            'seq': 'MAKRFGYSFQNFDPKRMARASARDLRISPKLAVEVCRELRGMMLNDALRYLDDVIALKRPVPLKRYNDSQGHKPGKGFGPGRYPVKVAKAIKKVLLNVKNNAVQKGLDPDKLKIIHIAAHKGPVLRGWYPRAFGRATPFNEQTTHIEVVVEEIRR'
        },
        "uL23": {
            'parent_id': '4V6U', 
            'auth_asym_id': 'BT', 
            'seq': 'MDPYKVIIRPVVTEKAISLIEKENKLTFIVDRRATKQDIKRAVEEIFNVKVEKVNTLITPRGEKKAYVKLKPEYSASEVAARLGLF'
        },
        "eL39": {
            'parent_id': '4V6U', 
            'auth_asym_id': 'Bf', 
            'seq': 'MARNKPLAKKLRLAKALKQNRRVPVWVIVKTNRRVLTHPKRRYWRRTKLKE'
        },
        "23S": {
            'parent_id': '4V6U', 
            'auth_asym_id': 'B1', 
            'seq': 'GGGCUAGGACGCUAAGCCGCCCGGUGGAUGGCUCGGCUCGGGGCGCCGACGAAGGGCGUGGCAAGCUGCGAUAAGCCCCGGCGAGGCGCAGGCAGCCGUCGAACCGGGGAUUCCCGAAUGGGACCUCCCGCGGCUUAUGCCGCACUCCGGGGUUUAUCCCCGGAGGGGGAACGCGGGGAAUUGAAACAUCUUAGUACCCGCAGGAAAAGAAAGCAAAAGCGAUGCCGUGAGUAGGGGCGACCGAAAACGGCAGAGGGCAAACUGAACCCCGGGCCGACGAGGUUCGGGGGAUGUGGGGUUGUAGGGCCCCCGUAUGAGACCCUCGCGGGUGAAGCCGAAGUCCGCUGGAACGCGGCGCCGGAGAGGGUGAUAGCCCCGUAGGCGUAAGCCCGCAGGGUCUCGGGGGACCCUGAGUACCGUCGGUUGGAUAUCCGGCGGGAAGCUGGGAGGCAUCGGCUCCCAACCCUAAAUACGUCCCGAGACCGAUAGCGAACUAGUACCGUGAGGGAAAGCUGAAAAGCACCCCGGGAGGGGGGUGAAAAGAGCCUGAAACCGGGCGGCGAUAGGAGGGUGCGGCCCGAAAGGAAUGAGCCUCCCCGAAGGAAACCGCGGCGACGCGGGAGUACGAGGGGAGGGGACCGGGGUUGCACCGUCCGUCUUGAAACACGGGGCAGGGAGUUCGCGGCCGUGGCGAGGUUAAGGGGGUUAAGCCCCGUAGCCGCAGGGAAACCGACAUGCCCGCAGCCGGGCUUAUGCCCGGUGAGGGGCGGGGUGCGAAAGCGCCCGGAGUCACGGCCGCGAGACCCGAAACCGGUCGAUCUAGCCCGGGGCAGGGUGAAGUCCCUCAACCGAGGGAUGGAGGCCCGCUAGGGGUGCUGAUGUGCAGUUCGCUCCCGUGACCCCGGGCUAGGGGUGAAAGGCCAAUCGAGGCCGGAGAUAGCUGGUUCCCGCCGAAUCAUCCCGCAGGAUGGCCUCCCCGGAGGUAGGCGGUGGGGUAGAGCACUGAUUGGAGGUGCAGGGGGCGAAAGCCCCCGGCCUCCUGUCAAACUCCGAACCCACCGCCGCCGUAGAUGGGGGGAGUAGGGUGGCGGUGUAAGCCGUCCACCGAGAGGGGAACAACCCAGACCGGGGUUAAGGCCCCAAAGUGCCGGCUAAGUGUUACUCCAAAGGGUGUCCCGGGCCUUAGACAGCGGGGAGGUAGGCUUAGAAGCAGCCAUCCUUUAAAGAGUGCGUAACAGCUCACCCGUCGAGGUCCGGGGCCCCGAAAAUGGACGGGGCUCAAGCCGGCCGCCGAGACCCCGGCGCACGGACCGAUUGGUCCGUGAUCGGGUAGGCGGGCGUGCCGGUGGCGUAGAAGCCGGGCCGUAAGGUCCGGUGGAGCCGCCGGUAUCGCGGAUCCUGCCGGGAGUAGCAGCGUAGUCGGGUGAGAAUCCCGACCGCCGGAGGGGCCAGGGUUCCACGGCAAUGGUCGUCAGCCGUGGGUUAGUCGGUCCUAACCCCGCCCGUAACUCGGCGCGGGGGAAAGGGAAACGGGUUUAUAUUCCCGUACCGCGGGGGUAGGUGCGGCAACGCAAGCCCGGAGGGUGACGCCUCGGGGUAGGCGGACCGGCCGAUGAGGCCGGCUAAGCGUAUAAGCCCGGGGAGUGCCGUAAUGGCGAGAACCGGGUGAAAGCGCGAAUGGCCCCCCCGUUAGGGGGGUUCCGCCGAUCCCUGGGGCCCGUGAAAAGCCCUCCGGGAAUUCCGAUCCCCCGCGACCGUACCGAGAACCGACACAGGUGCCCCUGGGUGAGAAGCCUAAGGCGUGUCGGGGGAAACCCGGCCGAGGGAACUCGGCAAACUGGCCCCGUAACUUCGGGAGAAGGGGUGCCUGCGGGUGCGUAACCCGCAGGUCGCAGUGACUAGGGGGGCCCGACUGUUUAAUAAAAACACAGGUCCCAGCUAGCCCGAAAGGGUUUGUACUGGGGCCGACGCCUGCCCAGUGCCGGUAUGUGAAGCCCGGGUACAACCGGGUGAAGCACCGGUAAACGGCGGGGGUAACUAUAACCCUCUUAAGGUAGCGAAAUUCCUUGUCGGUUAAAUGCCGACCUGCAUGAAUGGCGUAACGAGGUCCCCGCUGUCCCCGGCCGGGGCCCGGCGAAACCUCUGCCUGGCGCGCAUGCCAGGGACCCCCGGUGGGAAGCGAAGACCCCAUGGAGCUUUACUGCAGCCUGCCGUUGCCACACGGCGGGGGGUGCGCAGCGUAGGCGGGAGGCGUCGAAGCCCGGCCUCCGGGUCGGGUGGAGCCGUCCAUGAGACACCGCCCACUCCCCGCUGUGUGGCUAACCCCCGAAAGGGGGGACAGCGGUAGGUGGGCAGUUUGGCUGGGGCGGCACGCCUCCGAAAAGGUAUCGGAGGCGCCCUAAGGUCGGCUCAGGCGGGUCAGGAAUCCGCCGUAGAGUGCAAGGGCAAAAGCCGGCCUGACUGGACCCGUAACAGAGGCGGGUCCAGCCCCGAAAGGGUGGCCUAGCGAACCCCUGUGCCUCCCCGGUGGGGGCCAGGGAUGACAGAAAAGCUACCCUGGGGAUAACAGAGUCGUCUCGGGCGAGAGCCCAUAUCGACCCCGAGGCUUGCUACCUCGCUGUCGGCUCUUCCCAUCCUGGCCCUGCAGCAGGGGCCAAGGGUGGGGGUGUUCACCCAUUAAAGGGGAACGUGAGCUGGGUUUAGACCGUCGUGAGACAGGUCGGAUGCUAUCUACCGGGGGUGUUGGCCGCCUGAGGGGAAGGUGCCCCUAGUACGAGAGGAACAGGGUGCCGCGGCCUCUGGUCUACCGGUUGUCCUCCCGGGCAUCGCCGGGCAGCUACGCCGCAGCCGAUAAGGCCUGAAAGCAUCUAAGGCCGAAGCGGCCCCCGAAAAUAGGCGGCCGUUCCCUGGCGCUUGGGCCUGGGCGACCGGCCCAUUGCCAGGGACGAGGGCUCGGGUAGAAGACCCGGUUGAUAGGGCGGGGAUGUAAGCGGGAAGGGUCAACCGACCCGCUUAGUCCGCCGCCCCUAAUCGCCCGAGGUCCUGCCCC'
        }
    }
}


class ResidueSummary(BaseModel): 
    label_seq_id : typing.Optional[int] = None
    label_comp_id: typing.Optional[str] = None
    auth_asym_id : str
    auth_seq_id  : int
    rcsb_id:str
    full_id      : typing.Optional[tuple[str, int, str, tuple[str, int, str]]]

    @staticmethod
    def three_letter_code_to_one(resname: str):
        if resname in AMINO_ACIDS:
            return AMINO_ACIDS[resname]["one_letter_code"]
        elif resname in NUCLEOTIDES:
                return resname
        else:
            return '-'

    @staticmethod
    def one_letter_code_to_three(resname: str):
        if resname in [*map(lambda x: x[1]['one_letter_code'], AMINO_ACIDS.items())]:
            for tlk, d in AMINO_ACIDS.items():
                if d["one_letter_code"] == resname:
                    return tlk
        elif resname in NUCLEOTIDES:
                return resname
        else:
            return '-'

    def __hash__(self):
        return hash( self.get_resname() if self.get_resname() is not None else "" + str(self.get_seqid()) + self.get_parent_auth_asym_id() )

    def get_resname(self):
        return self.label_comp_id

    def get_seqid(self):
        (structure_id, model_id, chain_id, _) = self.full_id
        (hetero, seqid, insertion_code)       = _
        return seqid

    def get_parent_auth_asym_id(self):
        (structure_id, assembly_id, chain_id, _) = self.full_id
        return chain_id

    @staticmethod
    def from_biopython_residue(r: Residue):

        (structure_id, model_id, chain_id, _) = r.get_full_id()
        (hetero, seqid, insertion_code) = _

        return ResidueSummary(
            auth_seq_id   = seqid,
            label_seq_id  = None,
            label_comp_id = r.get_resname(),
            auth_asym_id  = chain_id,
            full_id       = r.get_full_id(),
            rcsb_id       = r.get_full_id()[0]
        )